const ACCOUNT_KEY="rfl_accounts_v2";
const SESSION_KEY="rfl_session_v2";
const encoder=new TextEncoder();
const b64=bytes=>btoa(String.fromCharCode(...bytes));
const unb64=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
const accounts=()=>{try{return JSON.parse(localStorage.getItem(ACCOUNT_KEY)||"[]")}catch{return[]}};
const save=value=>localStorage.setItem(ACCOUNT_KEY,JSON.stringify(value));
async function hash(secret,salt){const key=await crypto.subtle.importKey("raw",encoder.encode(secret),"PBKDF2",false,["deriveBits"]);return new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations:210000},key,256))}
function code(){const bytes=crypto.getRandomValues(new Uint8Array(9));const raw=Array.from(bytes,b=>b.toString(36).padStart(2,"0")).join("").toUpperCase();return `RFL-${raw.slice(0,4)}-${raw.slice(4,8)}-${raw.slice(8,12)}`}
const publicProfile=a=>({id:a.id,displayName:a.displayName,loginId:a.loginId,role:a.role,title:a.title,escapeeRank:a.escapeeRank,pursuerRank:a.pursuerRank,guest:false});
export class AccountService{
 getSession(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||"null")}catch{return null}}
 createGuest(){const p={id:`guest_${crypto.randomUUID()}`,displayName:"Player",loginId:null,role:"GUEST",title:null,escapeeRank:"ROOKIE",pursuerRank:"ROOKIE",guest:true};sessionStorage.setItem(SESSION_KEY,JSON.stringify(p));return p}
 async register({displayName,loginId,password,confirmPassword}){const name=displayName.trim(),login=loginId.trim().toLowerCase();if(name.length<3||name.length>16)throw Error("Display name must be 3 to 16 characters.");if(!/^[a-z0-9_]{4,20}$/.test(login))throw Error("Login ID must use 4 to 20 lowercase letters, numbers, or underscores.");if(password.length<12)throw Error("Password must contain at least 12 characters.");if(password!==confirmPassword)throw Error("Passwords do not match.");const list=accounts();if(list.some(a=>a.loginId===login))throw Error("That login ID already exists on this device.");const ps=crypto.getRandomValues(new Uint8Array(16)),rc=code(),rs=crypto.getRandomValues(new Uint8Array(16));const a={id:crypto.randomUUID(),displayName:name,loginId:login,role:"PLAYER",title:null,escapeeRank:"ROOKIE",pursuerRank:"ROOKIE",passwordSalt:b64(ps),passwordHash:b64(await hash(password,ps)),recoverySalt:b64(rs),recoveryHash:b64(await hash(rc,rs))};list.push(a);save(list);const p=publicProfile(a);sessionStorage.setItem(SESSION_KEY,JSON.stringify(p));return{profile:p,recoveryCode:rc}}
 async signIn(loginId,password){const a=accounts().find(x=>x.loginId===loginId.trim().toLowerCase());if(!a||b64(await hash(password,unb64(a.passwordSalt)))!==a.passwordHash)throw Error("Login ID or password is incorrect.");const p=publicProfile(a);sessionStorage.setItem(SESSION_KEY,JSON.stringify(p));return p}
 async resetPassword(loginId,recovery,newPassword){if(newPassword.length<12)throw Error("Password must contain at least 12 characters.");const list=accounts(),a=list.find(x=>x.loginId===loginId.trim().toLowerCase());if(!a)throw Error("Account was not found.");if(b64(await hash(recovery.trim().toUpperCase(),unb64(a.recoverySalt)))!==a.recoveryHash)throw Error("Recovery code is incorrect.");const ps=crypto.getRandomValues(new Uint8Array(16));a.passwordSalt=b64(ps);a.passwordHash=b64(await hash(newPassword,ps));const next=code(),rs=crypto.getRandomValues(new Uint8Array(16));a.recoverySalt=b64(rs);a.recoveryHash=b64(await hash(next,rs));save(list);return next}
 signOut(){sessionStorage.removeItem(SESSION_KEY)}
}
export function getChatIdentity(p){if(p.role==="ADMIN")return{label:"Admin",className:"admin"};if(p.role==="MODERATOR")return{label:"Mod",className:"moderator"};if(p.title==="LEGEND")return{label:"Legend",className:"legend"};if(p.role==="GUEST")return{label:"Guest",className:"guest"};return{label:"Player",className:"player"}}
