import * as THREE from "three";
import { createEscapee, createPursuer, CharacterAnimator } from "./characters.js";
import {
  addCoins,
  executeAdminCoinCommand,
  executeGiftCommand,
  getSelectedRank
} from "./economy.js";

const MATCH_TIME=600, PLAYER_HEIGHT=1.72, REQUIRED_TERMINALS=3, REPAIR_TIME=5;
const CAMERA_MODES=["FIRST","SECOND","THIRD"], UP=new THREE.Vector3(0,1,0);
const distanceXZ=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.78,metalness:.08,...extra});
const box=(name,size,pos,color,custom=null)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...size),custom||mat(color));m.name=name;m.position.set(...pos);return m};

function storedProfile(){
  for(const key of ["rfl_session_v3","rfl_session_v2","rfl_session_v1"]){
    try{const value=JSON.parse(sessionStorage.getItem(key)||"null");if(value?.displayName)return value}catch{}
  }
  return{id:"local_guest",displayName:"Player",loginId:null,role:"GUEST",title:null,guest:true};
}

function npcProfile(npc){return{id:npc.userData.entityId,loginId:npc.userData.entityId,displayName:npc.userData.name,role:"PLAYER",title:null,npc:true}}

export class Game{
  constructor(container,{role="ESCAPEE",onExit,onRetry,profile,profiles=[],onCoinsChanged}={}){
    Object.assign(this,{container,role,onExit,onRetry,onCoinsChanged});
    this.profile=profile||storedProfile();this.profiles=Array.isArray(profiles)?profiles:[];
    this.keys=new Set();this.escapees=[];this.pursuers=[];this.walls=[];this.obstacles=[];this.terminals=[];
    this.playerPosition=new THREE.Vector3();this.playerModel=null;this.playerAnimator=null;
    this.cameraModeIndex=0;this.cameraMode=CAMERA_MODES[0];this.cameraRay=new THREE.Raycaster();
    this.yaw=0;this.pitch=0;this.elapsed=0;this.stamina=100;this.repaired=0;this.repairProgress=0;
    this.running=false;this.ended=false;this.rewardGranted=false;this.chatOpen=false;this.chatMessages=[];this.chatMaximum=10;
    this.touch={sprint:false,sneak:false,interact:false};this.joystick={x:0,y:0,pointer:null};this.dragPointer=null;
    this.animate=this.animate.bind(this);this.keyDown=this.keyDown.bind(this);this.keyUp=this.keyUp.bind(this);this.mouseMove=this.mouseMove.bind(this);this.resize=this.resize.bind(this);
  }

  start(){
    this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x071119);this.scene.fog=new THREE.Fog(0x071119,22,95);
    this.camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,240);this.camera.rotation.order="YXZ";
    this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});
    this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(this.container.clientWidth,this.container.clientHeight,false);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.container.appendChild(this.renderer.domElement);
    this.clock=new THREE.Clock();this.createLighting();this.createFacility();this.createObjectives();this.createCharacters();this.createHud();this.createGameChat();this.createTouchControls();this.bindEvents();this.updateCamera();
    this.addSystemMessage(this.role==="PURSUER"?"Capture all four escapees.":"Restore three terminals and reach the exit.");
    this.running=true;this.clock.start();this.animate();
  }

  createLighting(){this.scene.add(new THREE.HemisphereLight(0x6c91a8,0x0d1113,1.25));const d=new THREE.DirectionalLight(0xb7ddeb,1.1);d.position.set(20,30,10);this.scene.add(d);const e=new THREE.PointLight(0xff2424,2,34,2);e.position.set(0,5,0);this.scene.add(e)}
  addWall(x,z,w,d){const m=box("Wall",[w,5,d],[x,2.5,z],0x38444a);this.scene.add(m);this.walls.push(m)}
  addCrate(x,z){const m=box("Crate",[3.4,2.6,3.4],[x,1.3,z],0x655f49);this.scene.add(m);this.obstacles.push(m)}
  createFacility(){
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),mat(0x222a2e));floor.rotation.x=-Math.PI/2;this.scene.add(floor);const grid=new THREE.GridHelper(100,50,0x4b5f69,0x343f45);grid.position.y=.01;this.scene.add(grid);
    [[0,-49,98,1],[0,49,98,1],[-49,0,1,98],[49,0,1,98],[-25,-20,1,38],[-25,26,1,34],[25,-24,1,34],[25,25,1,38],[0,-12,28,1],[8,12,30,1],[-18,34,28,1],[-36,4,20,1],[36,2,20,1]].forEach(v=>this.addWall(...v));
    [[-36,-34],[-31,-34],[-36,-29],[35,33],[30,33],[35,28],[6,-27],[11,-27],[6,-22],[-8,22],[-3,22],[16,26],[21,26]].forEach(v=>this.addCrate(...v));
  }

  createObjectives(){
    [[-38,0],[36,-30],[10,38]].forEach(([x,z],i)=>{const t=new THREE.Group();t.position.set(x,0,z);t.name=`Terminal${i+1}`;const sm=mat(0x681f1f,{emissive:0xff2020,emissiveIntensity:1.2});t.add(box("TerminalBody",[2,2.4,1.2],[0,1.2,0],0x263239),box("TerminalScreen",[1.3,.75,.08],[0,1.55,-.64],0,sm));t.userData={repaired:false,progress:0,screenMaterial:sm,assignedNpcId:null};this.scene.add(t);this.terminals.push(t)});
    this.exitGate=new THREE.Group();this.exitGate.position.set(0,0,-47.5);const f=mat(0x596871,{metalness:.5});this.exitGate.add(box("Frame",[1,5,1],[-3.5,2.5,0],0,f),box("Frame",[1,5,1],[3.5,2.5,0],0,f),box("Frame",[8,1,1],[0,4.5,0],0,f));const door=box("Door",[6,4,.5],[0,2,0],0x5a1818,mat(0x5a1818,{emissive:0x9d1515,emissiveIntensity:.5}));this.exitGate.add(door);this.exitGate.userData={open:false,door};this.scene.add(this.exitGate);
  }

  createCharacter(type,x,z,color,name){const c=type==="PURSUER"?createPursuer():createEscapee({jacketColor:color});c.position.set(x,0,z);Object.assign(c.userData,{entityId:crypto.randomUUID(),type,name,state:"IDLE",captured:false,escaped:false,health:2,stuckTime:0,avoidanceSide:Math.random()<.5?-1:1,targetTerminal:null,chatCooldownUntil:0,lastChatKey:"",animator:new CharacterAnimator(c)});this.scene.add(c);return c}
  createCharacters(){
    const sp=[[-8,36],[0,38],[8,36],[14,32]],colors=[0x3e8fd1,0x3fae72,0xb07bd8,0xd59a43],names=["NOVA-01","NOVA-02","NOVA-03","NOVA-04"],hunter=[-40,-12];
    if(this.role==="ESCAPEE"){this.playerPosition.set(0,0,34);this.yaw=Math.PI;this.playerModel=createEscapee({jacketColor:0xd59a43});sp.slice(0,3).forEach((p,i)=>this.escapees.push(this.createCharacter("ESCAPEE",p[0],p[1],colors[i],names[i])));this.pursuers.push(this.createCharacter("PURSUER",hunter[0],hunter[1],0x15191c,"WARDEN"))}
    else{this.playerPosition.set(hunter[0],0,hunter[1]);this.yaw=Math.PI/2;this.playerModel=createPursuer();sp.forEach((p,i)=>this.escapees.push(this.createCharacter("ESCAPEE",p[0],p[1],colors[i],names[i])))}
    this.playerModel.position.copy(this.playerPosition);this.playerModel.userData.animator=new CharacterAnimator(this.playerModel);this.playerAnimator=this.playerModel.userData.animator;this.scene.add(this.playerModel);this.syncPlayerModel();
  }

  createHud(){
    this.hud=document.createElement("div");this.hud.className="game-hud";this.hud.innerHTML=`<div class="hud-stack"><div class="hud-panel"><div class="hud-title">RUN FOR LIVE</div><div class="hud-row"><span>ROLE</span><strong>${this.role}</strong></div><div class="hud-row"><span>VIEW</span><strong data-view>FIRST</strong></div><div class="hud-row"><span>TIME</span><strong data-time>10:00</strong></div><div class="hud-row"><span>TERMINALS</span><strong data-terminals>0 / 3</strong></div><div class="hud-row"><span>CAPTURED</span><strong data-captured>0 / 4</strong></div><div class="hud-row"><span>ESCAPEES</span><strong data-active>4 ACTIVE</strong></div><div class="hud-row"><span>STAMINA</span><strong data-stamina>100%</strong></div></div></div><div class="crosshair"></div><div class="center-prompt" data-prompt></div><div class="view-toast" data-view-toast>FIRST PERSON</div>`;document.body.appendChild(this.hud);
    this.ui={view:this.hud.querySelector("[data-view]"),time:this.hud.querySelector("[data-time]"),terminals:this.hud.querySelector("[data-terminals]"),captured:this.hud.querySelector("[data-captured]"),active:this.hud.querySelector("[data-active]"),stamina:this.hud.querySelector("[data-stamina]"),prompt:this.hud.querySelector("[data-prompt]"),viewToast:this.hud.querySelector("[data-view-toast]")};
  }

  createGameChat(){
    this.chatRoot=document.createElement("section");this.chatRoot.className="game-chat";this.chatRoot.innerHTML=`<div class="game-chat__log" data-log></div><form class="game-chat__form" data-form hidden><input data-input maxlength="120" autocomplete="off" placeholder="Type a message and press Enter..."></form><div class="game-chat__hint">T: CHAT</div>`;document.body.appendChild(this.chatRoot);this.chatLog=this.chatRoot.querySelector("[data-log]");this.chatForm=this.chatRoot.querySelector("[data-form]");this.chatInput=this.chatRoot.querySelector("[data-input]");this.chatForm.onsubmit=e=>{e.preventDefault();this.submitPlayerChat()};this.chatInput.onkeydown=e=>{e.stopPropagation();if(e.code==="Escape"){e.preventDefault();this.closeChat(false)}};
  }
  openChat(){if(this.chatOpen||this.ended)return;this.chatOpen=true;this.keys.clear();document.exitPointerLock?.();this.chatForm.hidden=false;this.chatRoot.classList.add("game-chat--open");requestAnimationFrame(()=>this.chatInput.focus())}
  closeChat(clear=true){this.chatOpen=false;this.chatForm.hidden=true;this.chatRoot.classList.remove("game-chat--open");if(clear)this.chatInput.value="";this.renderer?.domElement.focus?.()}

  getCommandProfiles(){
    const current=[...this.escapees,...this.pursuers].map(npcProfile);
    const virtual=Array.from({length:1000},(_,i)=>{const n=String(i+1).padStart(4,"0");return{id:`npc_${n}`,loginId:`npc_${n}`,displayName:`NOVA-${n}`,role:"PLAYER",title:null,npc:true}});
    const all=[this.profile,...this.profiles,...current,...virtual];return all.filter((p,i,list)=>list.findIndex(x=>x.id===p.id)===i);
  }

  submitPlayerChat(){
    const content=this.chatInput.value.trim().slice(0,120);if(!content){this.closeChat(true);return}
    const coin=/^\/(?:coin\s+give|give\s+coin)\s+/i.test(content),gift=/^\/gift\s+/i.test(content);
    if(coin||gift){
      try{const result=coin?executeAdminCoinCommand({executor:this.profile,command:content,profiles:this.getCommandProfiles()}):executeGiftCommand({sender:this.profile,command:content,profiles:this.getCommandProfiles()});this.addSystemMessage(result.message);this.onCoinsChanged?.(result)}catch(error){this.addSystemMessage(error?.message||String(error))}
      this.closeChat(true);return;
    }
    let identity;if(this.profile.role==="ADMIN")identity={label:"Admin",className:"admin"};else if(this.profile.role==="MODERATOR")identity={label:"Mod",className:"moderator"};else if(this.profile.role==="GUEST")identity={label:"Guest",className:"guest"};else{const selected=getSelectedRank(this.profile);identity={label:selected.label,className:selected.className}}
    this.addChatMessage({...identity,displayName:this.profile.displayName,content});this.closeChat(true);
  }

  addChatMessage(message){this.chatMessages.push(message);if(this.chatMessages.length>this.chatMaximum)this.chatMessages.shift();this.renderChat()}
  addSystemMessage(content){this.addChatMessage({label:"System",className:"system",displayName:"",content})}
  addNpcMessage(npc,key,content,force=false){const now=performance.now();if(!force&&now<npc.userData.chatCooldownUntil)return;if(!force&&npc.userData.lastChatKey===key)return;npc.userData.chatCooldownUntil=now+8000+Math.random()*4000;npc.userData.lastChatKey=key;this.addChatMessage({label:npc.userData.type==="PURSUER"?"Pursuer":"Player",className:npc.userData.type==="PURSUER"?"pursuer":"player",displayName:npc.userData.name,content})}
  renderChat(){this.chatLog.replaceChildren(...this.chatMessages.map(m=>{const p=document.createElement("p"),id=document.createElement("span"),body=document.createElement("span");p.className="game-chat__line";id.className=`game-chat__identity game-chat__identity--${m.className}`;id.textContent=m.displayName?`[${m.label}] ${m.displayName}:`:`[${m.label}]`;body.className="game-chat__content";body.textContent=` ${m.content}`;p.append(id,body);return p}));this.chatLog.scrollTop=this.chatLog.scrollHeight}

  createTouchControls(){
    const root=document.createElement("div");root.id="touch-controls";root.innerHTML=`<div class="touch-look" data-look></div><div class="touch-stick" data-zone><div data-knob></div></div><div class="touch-buttons"><button data-run>RUN</button><button data-use>USE</button><button data-sneak>SNEAK</button><button data-view>VIEW</button><button data-chat>CHAT</button><button data-capture>${this.role==="PURSUER"?"CAPTURE":"PING"}</button></div>`;document.body.appendChild(root);this.touchRoot=root;
    const look=root.querySelector("[data-look]");look.onpointerdown=e=>{if(this.chatOpen)return;this.dragPointer=e.pointerId;this.dragX=e.clientX;this.dragY=e.clientY;look.setPointerCapture?.(e.pointerId)};look.onpointermove=e=>{if(e.pointerId!==this.dragPointer||this.chatOpen)return;this.yaw-=(e.clientX-this.dragX)*.005;this.pitch=THREE.MathUtils.clamp(this.pitch-(e.clientY-this.dragY)*.005,-1.25,1.25);this.dragX=e.clientX;this.dragY=e.clientY};look.onpointerup=()=>this.dragPointer=null;
    const zone=root.querySelector("[data-zone]"),knob=root.querySelector("[data-knob]");const stick=e=>{if(e.pointerId!==this.joystick.pointer||this.chatOpen)return;const b=zone.getBoundingClientRect();let x=e.clientX-(b.left+b.width/2),y=e.clientY-(b.top+b.height/2),len=Math.hypot(x,y);if(len>44){x=x/len*44;y=y/len*44}this.joystick.x=x/44;this.joystick.y=y/44;knob.style.transform=`translate(${x}px,${y}px)`};zone.onpointerdown=e=>{if(this.chatOpen)return;this.joystick.pointer=e.pointerId;zone.setPointerCapture?.(e.pointerId);stick(e)};zone.onpointermove=stick;zone.onpointerup=()=>{this.joystick={x:0,y:0,pointer:null};knob.style.transform="translate(0,0)"};
    const hold=(selector,key)=>{const control=root.querySelector(selector);control.onpointerdown=e=>{e.preventDefault();if(!this.chatOpen)this.touch[key]=true};control.onpointerup=control.onpointercancel=()=>this.touch[key]=false};hold("[data-run]","sprint");hold("[data-use]","interact");root.querySelector("[data-sneak]").onclick=()=>{if(!this.chatOpen)this.touch.sneak=!this.touch.sneak};root.querySelector("[data-view]").onclick=()=>{if(!this.chatOpen)this.cycleCameraMode()};root.querySelector("[data-chat]").onclick=()=>this.openChat();root.querySelector("[data-capture]").onclick=()=>{if(!this.chatOpen&&this.role==="PURSUER")this.tryCapture()};
  }

  bindEvents(){addEventListener("keydown",this.keyDown);addEventListener("keyup",this.keyUp);addEventListener("mousemove",this.mouseMove);addEventListener("resize",this.resize);this.renderer.domElement.onclick=()=>{if(!this.chatOpen)this.renderer.domElement.requestPointerLock?.()}}
  keyDown(e){if(this.chatOpen)return;if(e.code==="KeyT"&&!e.repeat){e.preventDefault();this.openChat();return}if(e.code==="Escape"){this.stop();this.onExit?.();return}if(e.code==="KeyC"&&!e.repeat){this.cycleCameraMode();return}if(e.code==="Space"&&this.role==="PURSUER")this.tryCapture();this.keys.add(e.code)}
  keyUp(e){if(this.chatOpen)return;this.keys.delete(e.code);if(e.code==="KeyE")this.repairProgress=0}
  mouseMove(e){if(this.chatOpen||document.pointerLockElement!==this.renderer.domElement)return;this.yaw-=e.movementX*.0023;this.pitch=THREE.MathUtils.clamp(this.pitch-e.movementY*.0023,-1.25,1.25)}
  cycleCameraMode(){this.cameraModeIndex=(this.cameraModeIndex+1)%CAMERA_MODES.length;this.cameraMode=CAMERA_MODES[this.cameraModeIndex];this.ui.view.textContent=this.cameraMode;this.ui.viewToast.textContent=this.cameraMode==="FIRST"?"FIRST PERSON":this.cameraMode==="SECOND"?"SECOND PERSON":"THIRD PERSON";this.ui.viewToast.classList.add("visible");clearTimeout(this.viewToastTimer);this.viewToastTimer=setTimeout(()=>this.ui.viewToast.classList.remove("visible"),1200);this.syncPlayerModel();this.updateCamera()}

  collision(x,z,r=.42){if(Math.abs(x)+r>47||Math.abs(z)+r>47)return true;return[...this.walls,...this.obstacles].some(o=>{const b=new THREE.Box3().setFromObject(o);return x+r>b.min.x&&x-r<b.max.x&&z+r>b.min.z&&z-r<b.max.z})}
  updatePlayer(dt){if(this.chatOpen){this.playerAnimator?.update(dt,{state:"IDLE"});return}let f=(this.keys.has("KeyW")?1:0)-(this.keys.has("KeyS")?1:0)-this.joystick.y,s=(this.keys.has("KeyD")?1:0)-(this.keys.has("KeyA")?1:0)+this.joystick.x;const sneak=this.keys.has("ShiftLeft")||this.keys.has("ShiftRight")||this.touch.sneak,run=((this.keys.has("KeyW")&&this.keys.has("KeyR"))||this.touch.sprint)&&f>.1&&!sneak&&this.stamina>0,speed=sneak?1.8:run?7.2:4.4;this.stamina=THREE.MathUtils.clamp(this.stamina+(run?-25:17)*dt,0,100);const l=Math.hypot(f,s);if(l>1){f/=l;s/=l}const move=new THREE.Vector3(-Math.sin(this.yaw),0,-Math.cos(this.yaw)).multiplyScalar(f).add(new THREE.Vector3(Math.cos(this.yaw),0,-Math.sin(this.yaw)).multiplyScalar(s));const x=this.playerPosition.x+move.x*speed*dt,z=this.playerPosition.z+move.z*speed*dt;if(!this.collision(x,this.playerPosition.z))this.playerPosition.x=x;if(!this.collision(this.playerPosition.x,z))this.playerPosition.z=z;this.syncPlayerModel();this.playerAnimator?.update(dt,{state:move.lengthSq()<.001?"IDLE":run?"RUN":"WALK"})}
  syncPlayerModel(){if(!this.playerModel)return;this.playerModel.position.copy(this.playerPosition);this.playerModel.rotation.y=this.yaw;this.playerModel.visible=this.cameraMode!=="FIRST"}
  updateCamera(){const eye=this.playerPosition.clone();eye.y+=PLAYER_HEIGHT;const forward=new THREE.Vector3(-Math.sin(this.yaw),0,-Math.cos(this.yaw));if(this.cameraMode==="FIRST"){this.camera.position.copy(eye);this.camera.rotation.set(this.pitch,this.yaw,0,"YXZ");return}const target=eye.clone();target.y-=.15;const desired=eye.clone();if(this.cameraMode==="SECOND"){desired.addScaledVector(forward,4.6);desired.y+=.55}else{desired.addScaledVector(forward,-5.7);desired.y+=1.5}const direction=desired.clone().sub(target),max=direction.length();direction.normalize();this.cameraRay.set(target,direction);this.cameraRay.far=max;const hits=this.cameraRay.intersectObjects([...this.walls,...this.obstacles],false),safe=hits.length?target.clone().addScaledVector(direction,Math.max(.7,hits[0].distance-.35)):desired;this.camera.position.lerp(safe,.22);this.camera.lookAt(target)}

  chooseNpcDirection(npc,desired){const r=npc.userData.type==="PURSUER"?.78:.52,side=npc.userData.avoidanceSide||1;for(const angle of[0,25*side,-25*side,50*side,-50*side,75*side,-75*side,110,-110,160,-160,180]){const candidate=desired.clone().applyAxisAngle(UP,THREE.MathUtils.degToRad(angle));if(!this.collision(npc.position.x+candidate.x*1.3,npc.position.z+candidate.z*1.3,r)){if(angle!==0&&angle!==180)npc.userData.avoidanceSide=Math.sign(angle)||side;return candidate}}return null}
  moveNpc(npc,target,speed,dt){const desired=target.clone().sub(npc.position).setY(0);if(desired.lengthSq()<.01)return;desired.normalize();const direction=this.chooseNpcDirection(npc,desired);if(!direction){npc.userData.stuckTime+=dt;if(npc.userData.stuckTime>.7){npc.userData.avoidanceSide*=-1;npc.userData.stuckTime=0}return}npc.userData.stuckTime=0;const r=npc.userData.type==="PURSUER"?.78:.52,x=npc.position.x+direction.x*speed*dt,z=npc.position.z+direction.z*speed*dt;if(!this.collision(x,npc.position.z,r))npc.position.x=x;if(!this.collision(npc.position.x,z,r))npc.position.z=z;const targetRotation=Math.atan2(direction.x,direction.z)+Math.PI,diff=THREE.MathUtils.euclideanModulo(targetRotation-npc.rotation.y+Math.PI,Math.PI*2)-Math.PI;npc.rotation.y+=diff*Math.min(1,dt*9)}
  setNpcState(npc,state){if(npc.userData.state===state)return;npc.userData.state=state;if(state==="FLEE")this.addNpcMessage(npc,"flee","The pursuer is here!");else if(state==="REPAIR")this.addNpcMessage(npc,"repair","Repairing a terminal.");else if(state==="ESCAPE")this.addNpcMessage(npc,"exit","The exit is open. Move!");else if(state==="CHASE"&&npc.userData.type==="PURSUER")this.addNpcMessage(npc,"chase","I found you.")}
  selectTerminalForNpc(npc){if(npc.userData.targetTerminal&&!npc.userData.targetTerminal.userData.repaired)return npc.userData.targetTerminal;const available=this.terminals.filter(t=>!t.userData.repaired).sort((a,b)=>distanceXZ(npc.position,a.position)-distanceXZ(npc.position,b.position)),terminal=available.find(t=>!t.userData.assignedNpcId||t.userData.assignedNpcId===npc.userData.entityId)||available[0];if(terminal){terminal.userData.assignedNpcId=npc.userData.entityId;npc.userData.targetTerminal=terminal}return terminal}
  updateEscapeeNpc(npc,dt){if(npc.userData.captured||npc.userData.escaped)return;const pursuer=this.role==="PURSUER"?{position:this.playerPosition}:this.pursuers[0],danger=pursuer?distanceXZ(npc.position,pursuer.position):Infinity;if(danger<13){this.setNpcState(npc,"FLEE");const away=npc.position.clone().sub(pursuer.position).setY(0);if(away.lengthSq()<.01)away.set(1,0,0);this.moveNpc(npc,npc.position.clone().add(away.normalize().multiplyScalar(12)),4.9,dt)}else if(this.repaired>=REQUIRED_TERMINALS){this.setNpcState(npc,"ESCAPE");this.moveNpc(npc,this.exitGate.position,3.9,dt);if(distanceXZ(npc.position,this.exitGate.position)<2){npc.userData.escaped=true;npc.visible=false;this.addSystemMessage(`${npc.userData.name} escaped.`)}}else{const terminal=this.selectTerminalForNpc(npc);if(!terminal)this.setNpcState(npc,"IDLE");else if(distanceXZ(npc.position,terminal.position)>2.1){this.setNpcState(npc,"WALK");this.moveNpc(npc,terminal.position,2.8,dt)}else{this.setNpcState(npc,"REPAIR");terminal.userData.progress+=dt/REPAIR_TIME*.55;if(terminal.userData.progress>=1)this.completeTerminal(terminal,npc)}}npc.userData.animator.update(dt,{state:npc.userData.state,injured:npc.userData.health===1})}
  updatePursuerNpc(npc,dt){const candidates=[{isPlayer:true,position:this.playerPosition},...this.escapees.filter(e=>!e.userData.captured&&!e.userData.escaped).map(e=>({isPlayer:false,entity:e,position:e.position}))];if(!candidates.length)return;candidates.sort((a,b)=>distanceXZ(npc.position,a.position)-distanceXZ(npc.position,b.position));const target=candidates[0],d=distanceXZ(npc.position,target.position);this.setNpcState(npc,d<24?"CHASE":"WALK");this.moveNpc(npc,target.position,d<24?4.7:2.4,dt);npc.userData.animator.update(dt,{state:npc.userData.state});if(d<1.25){if(target.isPlayer){this.addNpcMessage(npc,"caught","You're coming with me.",true);this.end("CAUGHT")}else{target.entity.userData.health-=1;if(target.entity.userData.health<=0)this.captureEscapee(target.entity);else target.entity.position.addScaledVector(target.entity.position.clone().sub(npc.position).setY(0).normalize(),3)}}}
  updateNpcs(dt){this.escapees.forEach(e=>this.updateEscapeeNpc(e,dt));if(this.role==="ESCAPEE")this.pursuers.forEach(p=>this.updatePursuerNpc(p,dt))}
  completeTerminal(terminal,npc=null){if(terminal.userData.repaired)return;terminal.userData.repaired=true;terminal.userData.progress=1;terminal.userData.screenMaterial.color.set(0x1f7848);terminal.userData.screenMaterial.emissive.set(0x29ff82);terminal.userData.assignedNpcId=null;this.repaired+=1;if(npc)this.addNpcMessage(npc,`terminal-${this.repaired}`,"Terminal restored!",true);this.escapees.forEach(e=>{if(e.userData.targetTerminal===terminal)e.userData.targetTerminal=null});if(this.repaired>=REQUIRED_TERMINALS){this.exitGate.userData.open=true;this.exitGate.userData.door.visible=false;this.addSystemMessage("All terminals restored. The exit is open.")}}
  updateObjectives(dt){if(this.role!=="ESCAPEE"||this.chatOpen)return;const use=this.keys.has("KeyE")||this.touch.interact,terminal=this.terminals.filter(t=>!t.userData.repaired).sort((a,b)=>distanceXZ(this.playerPosition,a.position)-distanceXZ(this.playerPosition,b.position))[0];this.ui.prompt.classList.remove("visible");if(terminal&&distanceXZ(this.playerPosition,terminal.position)<3.4){this.ui.prompt.textContent=use?`RESTORING ${Math.min(100,Math.round(this.repairProgress/REPAIR_TIME*100))}%`:"HOLD E / USE TO RESTORE";this.ui.prompt.classList.add("visible");if(use){this.repairProgress+=dt;if(this.repairProgress>=REPAIR_TIME){this.completeTerminal(terminal);this.repairProgress=0}}else this.repairProgress=0}else if(distanceXZ(this.playerPosition,this.exitGate.position)<4){this.ui.prompt.textContent=this.exitGate.userData.open?"PRESS E / USE TO ESCAPE":`${REQUIRED_TERMINALS-this.repaired} TERMINALS REMAINING`;this.ui.prompt.classList.add("visible");if(use&&this.exitGate.userData.open)this.end("ESCAPED")}else this.repairProgress=0}
  captureEscapee(target){if(target.userData.captured)return;target.userData.captured=true;target.visible=false;this.addSystemMessage(`${target.userData.name} was captured.`);this.checkMatchEnd()}
  tryCapture(){const target=this.escapees.filter(e=>!e.userData.captured&&!e.userData.escaped).sort((a,b)=>distanceXZ(this.playerPosition,a.position)-distanceXZ(this.playerPosition,b.position))[0];if(target&&distanceXZ(this.playerPosition,target.position)<2.2){target.userData.health-=1;this.addChatMessage({label:"Pursuer",className:"pursuer",displayName:this.profile.displayName,content:target.userData.health<=0?"Captured.":"You cannot escape."});if(target.userData.health<=0)this.captureEscapee(target)}}
  checkMatchEnd(){if(this.ended)return;const remaining=this.escapees.filter(e=>!e.userData.captured&&!e.userData.escaped),captured=this.escapees.filter(e=>e.userData.captured).length;if(this.role==="PURSUER"&&remaining.length===0)this.end(captured===this.escapees.length?"PURSUER WIN":"MATCH OVER")}
  calculateReward(result){let reward=25;if(this.role==="ESCAPEE"){reward+=this.repaired*100;if(result==="ESCAPED")reward+=400}else{reward+=this.escapees.filter(e=>e.userData.captured).length*150;if(result==="PURSUER WIN")reward+=500}return Math.max(0,Math.floor(reward))}
  grantMatchReward(result){if(this.rewardGranted||this.profile.role==="GUEST")return 0;this.rewardGranted=true;const reward=this.calculateReward(result);if(reward>0){addCoins(this.profile,reward);this.onCoinsChanged?.({profile:this.profile,amount:reward,result})}return reward}
  updateHud(){const remaining=Math.max(0,MATCH_TIME-this.elapsed);this.ui.time.textContent=`${String(Math.floor(remaining/60)).padStart(2,"0")}:${String(Math.floor(remaining%60)).padStart(2,"0")}`;this.ui.terminals.textContent=`${this.repaired} / ${REQUIRED_TERMINALS}`;const captured=this.escapees.filter(e=>e.userData.captured).length,active=this.escapees.filter(e=>!e.userData.captured&&!e.userData.escaped).length;this.ui.captured.textContent=`${captured} / ${this.escapees.length}`;this.ui.active.textContent=`${active+(this.role==="ESCAPEE"?1:0)} ACTIVE`;this.ui.stamina.textContent=`${Math.round(this.stamina)}%`}
  end(title){if(this.ended)return;this.ended=true;this.running=false;this.closeChat(false);document.exitPointerLock?.();const reward=this.grantMatchReward(title),overlay=document.createElement("section");overlay.className="overlay";overlay.innerHTML=`<article class="overlay-card"><h2>${title}</h2>${reward>0?`<p class="match-reward">+${reward.toLocaleString()} Coins</p>`:""}<div class="menu-actions"><button class="menu-button menu-button--primary" data-retry>RETRY</button><button class="menu-button" data-menu>MENU</button></div></article>`;document.body.appendChild(overlay);overlay.querySelector("[data-retry]").onclick=()=>{this.stop();this.onRetry?.()};overlay.querySelector("[data-menu]").onclick=()=>{this.stop();this.onExit?.()};this.overlay=overlay}
  animate(){if(!this.running)return;this.frame=requestAnimationFrame(this.animate);const dt=Math.min(this.clock.getDelta(),.05);this.elapsed+=dt;this.updatePlayer(dt);this.updateNpcs(dt);this.updateObjectives(dt);this.updateCamera();this.updateHud();this.checkMatchEnd();if(this.elapsed>=MATCH_TIME)this.end(this.role==="PURSUER"?"PURSUER WIN":"TIME EXPIRED");this.renderer.render(this.scene,this.camera)}
  resize(){this.camera.aspect=this.container.clientWidth/this.container.clientHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(this.container.clientWidth,this.container.clientHeight,false)}
  stop(){this.running=false;cancelAnimationFrame(this.frame);clearTimeout(this.viewToastTimer);removeEventListener("keydown",this.keyDown);removeEventListener("keyup",this.keyUp);removeEventListener("mousemove",this.mouseMove);removeEventListener("resize",this.resize);this.hud?.remove();this.chatRoot?.remove();this.touchRoot?.remove();this.overlay?.remove();this.renderer?.dispose();this.renderer?.domElement.remove()}
}
