import * as THREE from "three";
import {createEscapee,createPursuer,CharacterAnimator} from "./characters.js";
const PLAYER_HEIGHT=1.72,UP=new THREE.Vector3(0,1,0),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export class Game{
 constructor(container,{role="ESCAPEE",onExit,onRetry}={}){Object.assign(this,{container,role,onExit,onRetry});this.keys=new Set();this.escapees=[];this.pursuers=[];this.colliders=[];this.yaw=0;this.pitch=0;this.running=false;this.animate=this.animate.bind(this);this.key=this.key.bind(this);this.keyUp=this.keyUp.bind(this);this.mouse=this.mouse.bind(this)}
 start(){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x071119);this.camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.1,200);this.camera.position.set(0,PLAYER_HEIGHT,32);this.camera.rotation.order="YXZ";this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setSize(innerWidth,innerHeight);this.container.appendChild(this.renderer.domElement);this.scene.add(new THREE.HemisphereLight(0x91b4c8,0x101214,1.5));const floor=new THREE.Mesh(new THREE.PlaneGeometry(90,90),new THREE.MeshStandardMaterial({color:0x252c30}));floor.rotation.x=-Math.PI/2;this.scene.add(floor);this.addWall(0,-44,88,1);this.addWall(0,44,88,1);this.addWall(-44,0,1,88);this.addWall(44,0,1,88);this.addWall(-18,0,1,55);this.addWall(18,-12,1,44);this.addWall(10,18,30,1);this.createCharacters();this.createHud();addEventListener("keydown",this.key);addEventListener("keyup",this.keyUp);addEventListener("mousemove",this.mouse);this.renderer.domElement.onclick=()=>this.renderer.domElement.requestPointerLock?.();this.running=true;this.clock=new THREE.Clock();this.animate()}
 addWall(x,z,w,d){const m=new THREE.Mesh(new THREE.BoxGeometry(w,5,d),new THREE.MeshStandardMaterial({color:0x38444a}));m.position.set(x,2.5,z);this.scene.add(m);this.colliders.push(m)}
 createCharacters(){if(this.role==="ESCAPEE"){[[-7,35],[0,37],[7,35]].forEach((p,i)=>this.escapees.push(this.spawn(createEscapee({jacketColor:[0x3e8fd1,0x3fae72,0xb07bd8][i]}),p[0],p[1],"ESCAPEE")));this.pursuers.push(this.spawn(createPursuer(),-38,-12,"PURSUER"))}else{this.camera.position.set(-38,PLAYER_HEIGHT,-12);[[-8,35],[-2,37],[5,35],[12,32]].forEach((p,i)=>this.escapees.push(this.spawn(createEscapee({jacketColor:[0x3e8fd1,0x3fae72,0xb07bd8,0xd59a43][i]}),p[0],p[1],"ESCAPEE")))}}
 spawn(character,x,z,type){character.position.set(x,0,z);Object.assign(character.userData,{type,state:"WALK",captured:false,animator:new CharacterAnimator(character),avoid:Math.random()<.5?-1:1});this.scene.add(character);return character}
 createHud(){this.hud=document.createElement("div");this.hud.className="game-hud";this.hud.innerHTML=`<div class="hud-stack"><div class="hud-panel"><div class="hud-title">RUN FOR LIVE</div><div class="hud-row"><span>ROLE</span><strong>${this.role}</strong></div><div class="hud-row"><span>ESCAPEES</span><strong data-active>4 ACTIVE</strong></div></div></div><div class="crosshair"></div>`;document.body.appendChild(this.hud);this.active=this.hud.querySelector("[data-active]")}
 key(e){if(e.code==="Escape"){this.stop();this.onExit?.();return}if(e.code==="Space"&&this.role==="PURSUER")this.capture();this.keys.add(e.code)}keyUp(e){this.keys.delete(e.code)}mouse(e){if(document.pointerLockElement!==this.renderer.domElement)return;this.yaw-=e.movementX*.0023;this.pitch=THREE.MathUtils.clamp(this.pitch-e.movementY*.0023,-1.45,1.45)}
 collision(x,z,r=.45){if(Math.abs(x)+r>43||Math.abs(z)+r>43)return true;return this.colliders.some(o=>{const b=new THREE.Box3().setFromObject(o);return x+r>b.min.x&&x-r<b.max.x&&z+r>b.min.z&&z-r<b.max.z})}
 updatePlayer(dt){let f=(this.keys.has("KeyW")?1:0)-(this.keys.has("KeyS")?1:0),s=(this.keys.has("KeyD")?1:0)-(this.keys.has("KeyA")?1:0),l=Math.hypot(f,s);if(l>1){f/=l;s/=l}const forward=new THREE.Vector3(-Math.sin(this.yaw),0,-Math.cos(this.yaw)),right=new THREE.Vector3(Math.cos(this.yaw),0,-Math.sin(this.yaw)),move=forward.multiplyScalar(f).add(right.multiplyScalar(s)).multiplyScalar((this.keys.has("KeyR")?7:4.4)*dt),x=this.camera.position.x+move.x,z=this.camera.position.z+move.z;if(!this.collision(x,this.camera.position.z))this.camera.position.x=x;if(!this.collision(this.camera.position.x,z))this.camera.position.z=z;this.camera.rotation.set(this.pitch,this.yaw,0)}
 moveNpc(npc,target,speed,dt){const desired=target.clone().sub(npc.position).setY(0);if(desired.lengthSq()<.01)return;desired.normalize();let chosen=null;for(const deg of [0,30*npc.userData.avoid,-30*npc.userData.avoid,60*npc.userData.avoid,-60*npc.userData.avoid,120,-120,180]){const c=desired.clone().applyAxisAngle(UP,THREE.MathUtils.degToRad(deg));if(!this.collision(npc.position.x+c.x,npc.position.z+c.z,npc.userData.type==="PURSUER"?.75:.5)){chosen=c;break}}if(!chosen)return;const x=npc.position.x+chosen.x*speed*dt,z=npc.position.z+chosen.z*speed*dt;if(!this.collision(x,npc.position.z))npc.position.x=x;if(!this.collision(npc.position.x,z))npc.position.z=z;npc.rotation.y=Math.atan2(chosen.x,chosen.z)+Math.PI;npc.userData.animator.update(dt,{state:speed>4?"RUN":"WALK"})}
 updateNpc(dt){if(this.role==="ESCAPEE"){const hunter=this.pursuers[0],targets=[this.camera,...this.escapees.filter(e=>!e.userData.captured)],target=targets.sort((a,b)=>dist(hunter.position,a.position)-dist(hunter.position,b.position))[0];this.moveNpc(hunter,target.position,4.6,dt);if(dist(hunter.position,target.position)<1.2){if(target===this.camera)this.end("CAUGHT");else target.userData.captured=true}}else{for(const e of this.escapees){if(e.userData.captured)continue;const away=e.position.clone().sub(this.camera.position).setY(0);const target=e.position.clone().add(away.lengthSq()?away.normalize().multiplyScalar(10):new THREE.Vector3(10,0,0));this.moveNpc(e,target,4.7,dt)}}this.active.textContent=`${this.escapees.filter(e=>!e.userData.captured).length+(this.role==="ESCAPEE"?1:0)} ACTIVE`}
 capture(){const t=this.escapees.filter(e=>!e.userData.captured).sort((a,b)=>dist(this.camera.position,a.position)-dist(this.camera.position,b.position))[0];if(t&&dist(this.camera.position,t.position)<2.2)t.userData.captured=true}
 end(title){this.running=false;document.exitPointerLock?.();const o=document.createElement("section");o.className="overlay";o.innerHTML=`<article class="overlay-card"><h2>${title}</h2><div class="menu-actions"><button class="menu-button menu-button--primary" data-retry>RETRY</button><button class="menu-button" data-menu>MENU</button></div></article>`;document.body.appendChild(o);o.querySelector("[data-retry]").onclick=()=>{this.stop();this.onRetry?.()};o.querySelector("[data-menu]").onclick=()=>{this.stop();this.onExit?.()};this.overlay=o}
 animate(){if(!this.running)return;this.frame=requestAnimationFrame(this.animate);const dt=Math.min(this.clock.getDelta(),.05);this.updatePlayer(dt);this.updateNpc(dt);this.renderer.render(this.scene,this.camera)}
 stop(){this.running=false;cancelAnimationFrame(this.frame);removeEventListener("keydown",this.key);removeEventListener("keyup",this.keyUp);removeEventListener("mousemove",this.mouse);this.hud?.remove();this.overlay?.remove();this.renderer?.dispose();this.renderer?.domElement.remove()}
}
